blank_issues_enabled: false

contact_links:
  - name: ğŸ“š OpenCompass Documentation (å®˜æ–¹æ–‡æ¡£)
    url: https://opencompass.readthedocs.io/en/latest/
    about: Check if your question is answered in docs
  - name: ğŸ’¬ General questions (å¯»æ±‚å¸®åŠ©)
    url: https://github.com/open-compass/opencompass/discussions
    about: Ask general usage questions and discuss with other OpenCompass community members
  - name: ğŸŒ Explore OpenCompass (å®˜ç½‘)
    url: https://opencompass.org.cn/
    about: Get know more about OpenCompass
